# Generated by Django 5.0.4 on 2024-07-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0015_rename_notification_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='body',
            field=models.CharField(max_length=50),
        ),
    ]
