# Generated by Django 5.0.4 on 2024-07-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0016_alter_notifications_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='post',
            new_name='post_meep',
        ),
    ]
