# Generated by Django 5.0.4 on 2024-07-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0020_alter_profile_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='born',
            field=models.DateTimeField(verbose_name='born_date'),
        ),
    ]
