# Generated by Django 5.0.4 on 2024-07-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0022_alter_profile_born'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='born',
            new_name='born_date',
        ),
    ]
